export const physique = 26; // 体基础值
export const health = 0; // 额外气血
export const primaryAttribute = 76; // 基础主属性
export const luck = 6; // 运基础值
export const quality = 0; // 装等基础值
export const TbaseArmorPlus = 25; // T 基础防御强化等级
export const NbaseACKPlus = 475; // N 基础攻击强化等级
export const TbaseACKPlus = 260; // T 基础攻击强化等级
export const baseOMENPlus = 300; // 基础仇恨强化等级
export const baseCurePlus = 20; // 基础治疗强化等级
export const baseACK = 22; // 基础攻击
export const ACKToCure = 0.5; // 攻击 - 疗效
export const baseIntensionVal = 0; // 基础强度值
export const ACKToOMEN = 0.8; // 攻击 - 仇恨
export const physiqueToHp = 20; // 体 - 气血
export const DprimaryAttributeToACK = 0.4; // D 主属性 - 攻击
export const TprimaryAttributeToACK = 0.15; // T 主属性 - 攻击
export const DprimaryAttributeToIntension1 = 0.5; // D 刃战 主属性 - 强度
export const DprimaryAttributeToIntension2 = 0.6; // D 非刃战 主属性 - 强度
export const NprimaryAttributeToIntension = 0.4; // N 主属性 - 强度
export const TprimaryAttributeToIntension = 0.35; // T 主属性 - 强度
export const DprimaryAttributeToThump1 = 0.4; // D 刃战 主属性 - 会心
export const DprimaryAttributeToThump2 = 0.3; // D 非刃战 主属性 - 会心
export const NprimaryAttributeToThump = 0.4; // N 主属性 - 会心
export const TprimaryAttributeToThump1 = 0.3; // T 非斩风 主属性 - 会心
export const TprimaryAttributeToThump2 = 0.4; // T 斩风 主属性 - 会心
export const NprimaryAttributeToCure = 0.6; // N 主属性 - 治疗效果
export const TprimaryAttributeToHp = 10; // T 主属性 - 生命
export const TprimaryAttributeToOMEN = 1; // T 主属性 - 仇恨
export const TluckToFocus = 2.093922652; // T 运 - 专注
export const TluckToPenetrate = 1.254143646; // T 运 - 识破
export const DluckToFocus = 2.091254753; // D 运 - 专注
export const NluckToSpeed = 1.673003802; // N 运 - 急速
export const NluckToACK = 0.627376426; // N 运 - 法攻
export const TluckToACK = 0.629834254; // T 运 - 物攻
export const baseACKPlusQuality = 180; // 影响基础攻击强化等级的装等
export const NbaseAckPlusNum = 2.5; // N 影响基础攻击强化等级的系数
export const TbaseAckPlusNum = 2; // T 影响基础攻击强化等级的系数
export const DIntensionToIntension = 0.0589425120; // D 强度 - 精度百分比
export const NIntensionToIntension = 0.0588922550; // T 强度 - 精度百分比
export const TIntensionToIntension = 0.059; // N 强度 - 精度百分比
export const NIntensionToCure = 0.0294677630; // 强度 - 治疗效果
export const TIntensionToOMEN = 0.0474; // 强度 - 仇恨效果
